services:
  backend:
    container_name: api
    build:
      context: ./backend/nba-players-rater-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17
    container_name: local_pg
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER not provided in .env file!}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not provided in .env file!}
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB not provided in .env file!}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]

  pg_admin:
    image: dpage/pgadmin4
    container_name: local_pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:?PGADMIN_DEFAULT_EMAIL not provided in .env file!}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:?PGADMIN_DEFAULT_PASSWORD not provided in .env file!}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

volumes:
    pgdata:
    pgadmin-data: