name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Start and Wait for PostgreSQL
      run: |
        docker run --rm -d --network host postgres:17 \
          -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
          -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
          -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
          -p 5432:5432 \
          --health-cmd "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" \ # Use environment variables here
          --health-interval 10s \
          --health-timeout 5s \
          --health-retries 5 \
          --name temp_postgres

        docker wait temp_postgres

        docker stop temp_postgres
        docker rm temp_postgres

    - name: Build and push backend
      uses: docker/build-push-action@v3
      with:
        context: ./backend/nba-players-rater-api
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/backend-service:latest
          ${{ secrets.DOCKER_USERNAME }}/backend-service:${{ github.sha }}
        build-args: |
          SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          SPRING_PROFILES_ACTIVE=dev
          
    - name: Build and push frontend
      uses: docker/build-push-action@v3
      with:
        context: ./frontend/nba-player-rater-frontend
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/frontend-service:latest
          ${{ secrets.DOCKER_USERNAME }}/frontend-service:${{ github.sha }}
        build-args: |
          VITE_REACT_APP_API_BASE_URL=${{ secrets.VITE_REACT_APP_API_BASE_URL }}
